[package]
name = "krunkit"
version = "0.1.0"
authors = ["Tyler Fanelli <tfanelli@redhat.com>"]
license = "Apache-2.0"
edition = "2021"
readme = "README.md"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.0", features = ["derive"] }
